### ISSUE TITLE
Great video - (question)

### ISSUE THREAD

**Issue by Aglomation** [KianBrose/smtp_mail_bot_server#2]
as i said above, Great video really liked it :) i'm guessing this code only catches the emails? do you have the rest of the code that actually opens the link, and btw what do you use for the regex?

Hope you have a great day and thank you for reading this :)

**Comment by KianBrose** [comment]
Hello!
Correct, this code is the "catch all" part of the mail server, the actual verification part was omitted and is available on patreon so that i could monetise the work to some degree

I used regex101 for regex testing
